export const Config = {
    bottraining : {
        'PendingQuestions': 'Pending Questions',
        'Send' : 'Send',
        'Word' : 'Word',
        'Type' : 'Type',
        'Value' : 'Value',
        'Status' : 'Status',
        'Add' : 'Add',
        'AddModify' : 'Add and Modify Intent',
        'Intent' : 'Intent',
        'SubIntent' : 'SubIntent',
        'ExistingSyn' : 'Existing Synonyms For',
        'AddSyn' : 'Add Synonym',
        'AddInt' : 'Add Intent',
        'AddSubint' : 'Add SubIntent',
        'ExistingSyno' : 'Existing synonyms',
        'Close' : 'Close',
        'Addnode' : 'Add Node',
        'SameAs' : 'same as',
        'Priority' : 'Priority',
        'AddSyno' : 'Add Synonyms for',
        'Synonyms' : 'Synonyms',
        'AddedSyn' : 'Suggested Synonyms',
        'SelectIntent' : 'Select Intent',
        'SelectAll' : 'Select All',
        'UnSelectAll' : 'UnSelect All',
        'myclass' : 'myclass custom-class',
        'SelectContext' : 'Select Context',
        'NotFound' : 'Not Found',
        'Video' : 'Video',
        'Link' : 'Link',
        'Counter' : 'Counter',
        'addedsucces' : 'Add successfully',
        'pleasefill' : 'please fill the fields',
        'SuccAdded' : 'Successfully Added',
        'alreadyexist' : 'Already existing prority',
        'deleted':"Successfully Deleted",
        'Question':'Question',
    }
}